export const currency = [
  { value: "ADP", label: "Andorran Peseta - ADP" },
  { value: "AED", label: "United Arab Emirates Dirham - AED" },
  { value: "AFA", label: "Afghanistan Afghani - AFA" },
  { value: "ALL", label: "Albanian Lek - ALL" },
  { value: "ANG", label: "Netherlands Antillian Guilder - ANG" },
  { value: "AOK", label: "Angolan Kwanza - AOK" },
  { value: "ARS", label: "Argentine Peso - ARS" },
  { value: "AUD", label: "Australian Dollar - AUD" },
  { value: "AWG", label: "Aruban Florin - AWG" },
  { value: "BBD", label: "Barbados Dollar - BBD" },
  { value: "BDT", label: "Bangladeshi Taka - BDT" },
  { value: "BGN", label: "Bulgarian Lev - BGN" },
  { value: "BHD", label: "Bahraini Dinar - BHD" },
  { value: "BIF", label: "Burundi Franc - BIF" },
  { value: "BMD", label: "Bermudian Dollar - BMD" },
  { value: "BND", label: "Brunei Dollar - BND" },
  { value: "BOB", label: "Bolivian Boliviano - BOB" },
  { value: "BRL", label: "Brazilian Real - BRL" },
  { value: "BSD", label: "Bahamian Dollar - BSD" },
  { value: "BTN", label: "Bhutan Ngultrum - BTN" },
  { value: "BUK", label: "Burma Kyat - BUK" },
  { value: "BWP", label: "Botswanian Pula - BWP" },
  { value: "BZD", label: "Belize Dollar - BZD" },
  { value: "CAD", label: "Canadian Dollar - CAD" },
  { value: "CHF", label: "Swiss Franc - CHF" },
  { value: "CLF", label: "Chilean Unidades de Fomento - CLF" },
  { value: "CLP", label: "Chilean Peso - CLP" },
  { value: "CNY", label: "Yuan (Chinese) Renminbi - CNY" },
  { value: "COP", label: "Colombian Peso - COP" },
  { value: "CRC", label: "Costa Rican Colon - CRC" },
  { value: "CZK", label: "Czech Republic Koruna - CZK" },
  { value: "CUP", label: "Cuban Peso - CUP" },
  { value: "CVE", label: "Cape Verde Escudo - CVE" },
  { value: "CYP", label: "Cyprus Pound - CYP" },
  { value: "DKK", label: "Danish Krone - DKK" },
  { value: "DOP", label: "Dominican Peso - DOP" },
  { value: "DZD", label: "Algerian Dinar - DZD" },
  { value: "ECS", label: "Ecuador Sucre - ECS" },
  { value: "EGP", label: "Egyptian Pound - EGP" },
  { value: "EEK", label: "Estonian Kroon (EEK) - EEK" },
  { value: "ETB", label: "Ethiopian Birr - ETB" },
  { value: "EUR", label: "Euro - EUR" },
  { value: "FJD", label: "Fiji Dollar - FJD" },
  { value: "FKP", label: "Falkland Islands Pound - FKP" },
  { value: "GBP", label: "British Pound - GBP" },
  { value: "GHC", label: "Ghanaian Cedi - GHC" },
  { value: "GIP", label: "Gibraltar Pound - GIP" },
  { value: "GMD", label: "Gambian Dalasi - GMD" },
  { value: "GNF", label: "Guinea Franc - GNF" },
  { value: "GTQ", label: "Guatemalan Quetzal - GTQ" },
  { value: "GWP", label: "Guinea-Bissau Peso - GWP" },
  { value: "GYD", label: "Guyanan Dollar - GYD" },
  { value: "HKD", label: "Hong Kong Dollar - HKD" },
  { value: "HNL", label: "Honduran Lempira - HNL" },
  { value: "HTG", label: "Haitian Gourde - HTG" },
  { value: "HUF", label: "Hungarian Forint - HUF" },
  { value: "IDR", label: "Indonesian Rupiah - IDR" },
  { value: "IEP", label: "Irish Punt - IEP" },
  { value: "ILS", label: "Israeli Shekel - ILS" },
  { value: "INR", label: "Indian Rupee - INR" },
  { value: "IQD", label: "Iraqi Dinar - IQD" },
  { value: "IRR", label: "Iranian Rial - IRR" },
  { value: "JMD", label: "Jamaican Dollar - JMD" },
  { value: "JOD", label: "Jordanian Dinar - JOD" },
  { value: "JPY", label: "Japanese Yen - JPY" },
  { value: "KES", label: "Kenyan Schilling - KES" },
  { value: "KHR", label: "Kampuchean (Cambodian) Riel - KHR" },
  { value: "KMF", label: "Comoros Franc - KMF" },
  { value: "KPW", label: "North Korean Won - KPW" },
  { value: "KRW", label: "(South) Korean Won - KRW" },
  { value: "KWD", label: "Kuwaiti Dinar - KWD" },
  { value: "KYD", label: "Cayman Islands Dollar - KYD" },
  { value: "LAK", label: "Lao Kip - LAK" },
  { value: "LBP", label: "Lebanese Pound - LBP" },
  { value: "LKR", label: "Sri Lanka Rupee - LKR" },
  { value: "LRD", label: "Liberian Dollar - LRD" },
  { value: "LSL", label: "Lesotho Loti - LSL" },
  { value: "LYD", label: "Libyan Dinar - LYD" },
  { value: "MAD", label: "Moroccan Dirham - MAD" },
  { value: "MGF", label: "Malagasy Franc - MGF" },
  { value: "MNT", label: "Mongolian Tugrik - MNT" },
  { value: "MOP", label: "Macau Pataca - MOP" },
  { value: "MRO", label: "Mauritanian Ouguiya - MRO" },
  { value: "MTL", label: "Maltese Lira - MTL" },
  { value: "MUR", label: "Mauritius Rupee - MUR" },
  { value: "MVR", label: "Maldive Rufiyaa - MVR" },
  { value: "MWK", label: "Malawi Kwacha - MWK" },
  { value: "MXP", label: "Mexican Peso - MXP" },
  { value: "MYR", label: "Malaysian Ringgit - MYR" },
  { value: "MZM", label: "Mozambique Metical - MZM" },
  { value: "NAD", label: "Namibian Dollar - NAD" },
  { value: "NGN", label: "Nigerian Naira - NGN" },
  { value: "NIO", label: "Nicaraguan Cordoba - NIO" },
  { value: "NOK", label: "Norwegian Kroner - NOK" },
  { value: "NPR", label: "Nepalese Rupee - NPR" },
  { value: "NZD", label: "New Zealand Dollar - NZD" },
  { value: "OMR", label: "Omani Rial - OMR" },
  { value: "PAB", label: "Panamanian Balboa - PAB" },
  { value: "PEN", label: "Peruvian Nuevo Sol - PEN" },
  { value: "PGK", label: "Papua New Guinea Kina - PGK" },
  { value: "PHP", label: "Philippine Peso - PHP" },
  { value: "PKR", label: "Pakistan Rupee - PKR" },
  { value: "PLN", label: "Polish Zloty - PLN" },
  { value: "PYG", label: "Paraguay Guarani - PYG" },
  { value: "QAR", label: "Qatari Rial - QAR" },
  { value: "RON", label: "Romanian Leu - RON" },
  { value: "RWF", label: "Rwanda Franc - RWF" },
  { value: "SAR", label: "Saudi Arabian Riyal - SAR" },
  { value: "SBD", label: "Solomon Islands Dollar - SBD" },
  { value: "SCR", label: "Seychelles Rupee - SCR" },
  { value: "SDP", label: "Sudanese Pound - SDP" },
  { value: "SEK", label: "Swedish Krona - SEK" },
  { value: "SGD", label: "Singapore Dollar - SGD" },
  { value: "SHP", label: "St. Helena Pound - SHP" },
  { value: "SLL", label: "Sierra Leone Leone - SLL" },
  { value: "SOS", label: "Somali Schilling - SOS" },
  { value: "SRG", label: "Suriname Guilder - SRG" },
  { value: "STD", label: "Sao Tome and Principe Dobra - STD" },
  { value: "RUB", label: "Russian Ruble - RUB" },
  { value: "SVC", label: "El Salvador Colon - SVC" },
  { value: "SYP", label: "Syrian Potmd - SYP" },
  { value: "SZL", label: "Swaziland Lilangeni - SZL" },
  { value: "THB", label: "Thai Baht - THB" },
  { value: "TND", label: "Tunisian Dinar - TND" },
  { value: "TOP", label: "Tongan Paanga - TOP" },
  { value: "TPE", label: "East Timor Escudo - TPE" },
  { value: "TRY", label: "Turkish Lira - TRY" },
  { value: "TTD", label: "Trinidad and Tobago Dollar - TTD" },
  { value: "TWD", label: "Taiwan Dollar - TWD" },
  { value: "TZS", label: "Tanzanian Schilling - TZS" },
  { value: "UGX", label: "Uganda Shilling - UGX" },
  { value: "USD", label: "US Dollar - USD" },
  { value: "UYU", label: "Uruguayan Peso - UYU" },
  { value: "VEF", label: "Venezualan Bolivar - VEF" },
  { value: "VND", label: "Vietnamese Dong - VND" },
  { value: "VUV", label: "Vanuatu Vatu - VUV" },
  { value: "WST", label: "Samoan Tala - WST" },
  { value: "XAG", label: "Silver, Ounces - XAG" },
  { value: "XAU", label: "Gold, Ounces - XAU" },
  { value: "XCD", label: "East Caribbean Dollar - XCD" },
  { value: "XPD", label: "Palladium Ounces - XPD" },
  { value: "XPT", label: "Platinum, Ounces - XPT" },
  { value: "YDD", label: "Democratic Yemeni Dinar - YDD" },
  { value: "YER", label: "Yemeni Rial - YER" },
  { value: "YUD", label: "New Yugoslavia Dinar - YUD" },
  { value: "ZAR", label: "South African Rand - ZAR" },
  { value: "ZMK", label: "Zambian Kwacha - ZMK" },
  { value: "ZRZ", label: "Zaire Zaire - ZRZ" },
  { value: "ZWD", label: "Zimbabwe Dollar - ZWD" },
  { value: "SKK", label: "Slovak Koruna - SKK" },
  { value: "AMD", label: "Armenian Dram - AMD" },
];
